# Base configs
baseurl: "https://rasmus1610.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"

# UI configs
title: "Marius Vach Photography"
subtitle: "Analog Black and White Photography"
author: "Marius Vach"
header:
 title: "Photography"
 subtitle: "by Marius Vach"
footer:
 name: "Hey there, my name is Marius"
 bio: "I am a physician from germany and a lover of analog black and white photography. Go and check out my work!"
web_design: "MV"
social_urls:
  instagram: "https://www.instagram.com/marius.35mm"
  github: "https://www.github.com/rasmus1610"
